<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\Type;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $lab = Type::firstOrCreate(['name' => 'Peralatan Laboratorium']);
        $furniture = Type::firstOrCreate(['name' => 'Perabotan Rumah Sakit']);
        $imaging = Type::firstOrCreate(['name' => 'Peralatan Pencitraan']);
        $it = Type::firstOrCreate(['name' => 'Peralatan TI']);
        $network = Type::firstOrCreate(['name' => 'Peralatan Jaringan']);
        $medical = Type::firstOrCreate(['name' => 'Perangkat Medis']);
        $office = Type::firstOrCreate(['name' => 'Peralatan Kantor']);

        $kp = User::where('code', 'KEPERAWATAN')->first();
        $upa = User::where('code', 'UPATIK')->first();
        $rpl = User::where('code', 'RPLUNIT')->first();
        $ti = User::where('code', 'TIUNIT')->first();
        $umum = User::where('code', 'UMUM')->first();

        $items = [
            [
                'id' => '3080205999-1',
                'user_id' => $kp?->id,
                'type_id' => $lab->id,
                'code' => '3080205999',
                'order_number' => '1',
                'name' => 'Biosafety Cabinet Class II, Type A2 (BSC-1003IIA2)',
                'cost' => 120000000,
                'acquisition_date' => '2025-03-01',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3050201010-1',
                'user_id' => $kp?->id,
                'type_id' => $furniture->id,
                'code' => '3050201010',
                'order_number' => '1',
                'name' => 'Hospital Bed Psikiatry (Karixa)',
                'cost' => 80000000,
                'acquisition_date' => '2025-05-10',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3070106150-1',
                'user_id' => $kp?->id,
                'type_id' => $imaging->id,
                'code' => '3070106150',
                'order_number' => '1',
                'name' => 'Karixa X-Ray Film Viewer',
                'cost' => 25000000,
                'acquisition_date' => '2025-06-15',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],

            [
                'id' => '4110002001-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002001',
                'order_number' => '1',
                'name' => 'Cisco Catalyst 2960 Switch 24-Port',
                'cost' => 15000000,
                'acquisition_date' => '2020-02-12',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002002-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002002',
                'order_number' => '1',
                'name' => 'Mikrotik Router RB4011',
                'cost' => 5000000,
                'acquisition_date' => '2019-11-20',
                'acquisition_year' => 2019,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3020101101-1',
                'user_id' => $upa?->id,
                'type_id' => $it->id,
                'code' => '3020101101',
                'order_number' => '1',
                'name' => 'Epson Projector EB-X500',
                'cost' => 7000000,
                'acquisition_date' => '2020-08-05',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],

            [
                'id' => '5050101001-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101001',
                'order_number' => '1',
                'name' => 'Creality Ender-3 3D Printer',
                'cost' => 4500000,
                'acquisition_date' => '2022-07-18',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101001-2',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101001',
                'order_number' => '2',
                'name' => 'Hakko FX-888D Soldering Station',
                'cost' => 2500000,
                'acquisition_date' => '2020-04-09',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101003-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101003',
                'order_number' => '1',
                'name' => 'Rigol DS1054Z Oscilloscope',
                'cost' => 9000000,
                'acquisition_date' => '2025-03-27',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],

            [
                'id' => '3030201001-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201001',
                'order_number' => '1',
                'name' => 'HP Z4 Workstation',
                'cost' => 35000000,
                'acquisition_date' => '2022-01-11',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201002-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201002',
                'order_number' => '1',
                'name' => 'APC Smart-UPS 1500VA',
                'cost' => 8000000,
                'acquisition_date' => '2025-09-22',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201003-1',
                'user_id' => $ti?->id,
                'type_id' => $network->id,
                'code' => '3030201003',
                'order_number' => '1',
                'name' => 'Fluke Network Analyzer',
                'cost' => 20000000,
                'acquisition_date' => '2025-05-30',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206000-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206000',
                'order_number' => '1',
                'name' => 'Patient Monitor Multiparameter',
                'cost' => 32000000,
                'acquisition_date' => '2025-07-12',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206001-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206001',
                'order_number' => '1',
                'name' => 'Defibrillator AED',
                'cost' => 45000000,
                'acquisition_date' => '2025-07-20',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206002-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206002',
                'order_number' => '1',
                'name' => 'Syringe Pump',
                'cost' => 15000000,
                'acquisition_date' => '2025-08-05',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206003-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206003',
                'order_number' => '1',
                'name' => 'Portable Suction Machine',
                'cost' => 8000000,
                'acquisition_date' => '2025-08-18',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206004-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206004',
                'order_number' => '1',
                'name' => 'Nebulizer Compressor',
                'cost' => 4000000,
                'acquisition_date' => '2025-09-02',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206005-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206005',
                'order_number' => '1',
                'name' => 'Oxygen Concentrator 5L',
                'cost' => 12000000,
                'acquisition_date' => '2025-09-20',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3080206006-1',
                'user_id' => $kp?->id,
                'type_id' => $medical->id,
                'code' => '3080206006',
                'order_number' => '1',
                'name' => 'ECG Machine 12-Lead',
                'cost' => 28000000,
                'acquisition_date' => '2025-10-01',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002003-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002003',
                'order_number' => '1',
                'name' => 'Aruba AP-515 Access Point',
                'cost' => 9000000,
                'acquisition_date' => '2020-09-14',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002004-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002004',
                'order_number' => '1',
                'name' => 'Ubiquiti UniFi AP-AC-Pro',
                'cost' => 3500000,
                'acquisition_date' => '2020-10-02',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002005-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002005',
                'order_number' => '1',
                'name' => 'Fortigate 60F Firewall',
                'cost' => 18000000,
                'acquisition_date' => '2020-11-11',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3020101102-1',
                'user_id' => $upa?->id,
                'type_id' => $it->id,
                'code' => '3020101102',
                'order_number' => '1',
                'name' => 'Synology NAS DS920+',
                'cost' => 14000000,
                'acquisition_date' => '2020-12-08',
                'acquisition_year' => 2020,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002006-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002006',
                'order_number' => '1',
                'name' => 'Patch Panel 24-Port Cat6',
                'cost' => 1500000,
                'acquisition_date' => '2019-01-15',
                'acquisition_year' => 2019,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002007-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002007',
                'order_number' => '1',
                'name' => 'Kabel Cat6 305m',
                'cost' => 2500000,
                'acquisition_date' => '2019-03-10',
                'acquisition_year' => 2019,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '4110002008-1',
                'user_id' => $upa?->id,
                'type_id' => $network->id,
                'code' => '4110002008',
                'order_number' => '1',
                'name' => 'Fiber Media Converter',
                'cost' => 3000000,
                'acquisition_date' => '2019-04-21',
                'acquisition_year' => 2019,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101004-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101004',
                'order_number' => '1',
                'name' => 'Fluke 115 Digital Multimeter',
                'cost' => 3500000,
                'acquisition_date' => '2025-08-08',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101005-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101005',
                'order_number' => '1',
                'name' => 'Logic Analyzer 16-Channel',
                'cost' => 2000000,
                'acquisition_date' => '2025-09-12',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101006-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101006',
                'order_number' => '1',
                'name' => 'Hot Air Rework Station 858D',
                'cost' => 1800000,
                'acquisition_date' => '2025-10-01',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101007-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101007',
                'order_number' => '1',
                'name' => 'Bench Power Supply 0-30V 5A',
                'cost' => 3500000,
                'acquisition_date' => '2025-10-20',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101008-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101008',
                'order_number' => '1',
                'name' => 'Reflow Oven',
                'cost' => 7000000,
                'acquisition_date' => '2022-02-02',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101009-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101009',
                'order_number' => '1',
                'name' => 'Arduino Mega 2560 Kit',
                'cost' => 1500000,
                'acquisition_date' => '2022-03-15',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '5050101010-1',
                'user_id' => $rpl?->id,
                'type_id' => $it->id,
                'code' => '5050101010',
                'order_number' => '1',
                'name' => 'Raspberry Pi 4 Model B',
                'cost' => 1200000,
                'acquisition_date' => '2022-04-10',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201004-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201004',
                'order_number' => '1',
                'name' => 'X-Rite i1Display Monitor Calibrator',
                'cost' => 4000000,
                'acquisition_date' => '2022-02-14',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201005-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201005',
                'order_number' => '1',
                'name' => 'Monitor 27" 4K',
                'cost' => 6500000,
                'acquisition_date' => '2022-03-01',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201006-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201006',
                'order_number' => '1',
                'name' => 'NAS Backup 8TB',
                'cost' => 10000000,
                'acquisition_date' => '2025-12-10',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201007-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201007',
                'order_number' => '1',
                'name' => 'Laptop ThinkPad T14',
                'cost' => 18000000,
                'acquisition_date' => '2022-05-10',
                'acquisition_year' => 2022,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201008-1',
                'user_id' => $ti?->id,
                'type_id' => $office->id ?? $it->id,
                'code' => '3030201008',
                'order_number' => '1',
                'name' => 'Printer Laser Monokrom',
                'cost' => 3500000,
                'acquisition_date' => '2025-08-18',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201009-1',
                'user_id' => $ti?->id,
                'type_id' => $office->id ?? $it->id,
                'code' => '3030201009',
                'order_number' => '1',
                'name' => 'Scanner Dokumen A4',
                'cost' => 2800000,
                'acquisition_date' => '2025-09-12',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
            [
                'id' => '3030201010-1',
                'user_id' => $ti?->id,
                'type_id' => $it->id,
                'code' => '3030201010',
                'order_number' => '1',
                'name' => 'KVM Switch 4-Port',
                'cost' => 2200000,
                'acquisition_date' => '2025-10-10',
                'acquisition_year' => 2025,
                'status' => 'AVAILABLE',
            ],
        ];

        foreach ($items as $data) {
            if ($data['user_id']) {
                $data['id'] = $data['code'] . '-' . $data['order_number'];
                Item::firstOrCreate(['id' => $data['id']], $data);
            }
        }
    }
}
